library(sqldf)
power <- read.csv.sql("household_power_consumption.txt", sql= "select * from file where Date in ('1/2/2007', '2/2/2007')", header = TRUE, sep = ';')
png("Plot2.png")
power$newdate <- with(power, as.POSIXct(paste(Date, Time), format = "%d/%m/%Y %H:%M:%S"))
plot(power$newdate, power$Global_active_power, type = "n", ylab = "Global Active Power (kilowatts)", xlab = "")
lines(power$newdate, power$Global_active_power)
dev.off()
